### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by roccivic**
## Description
Fixed typo

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/hill-a/stable-baselines/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/hill-a/stable-baselines/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the [changelog](https://github.com/hill-a/stable-baselines/blob/master/docs/misc/changelog.rst) accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [x] I have updated the documentation accordingly.
- [ ] I have ensured `pytest` and `pytype` both pass (by running  `make pytest` and `make type`).

### CODE REVIEW

**Comment by Miffyli** [comment]
Thanks for the PR! Please make sure to complete all points in the checklist (changelog) :).

Merging this will have to wait till some CI problems have been addressed.

**Comment by roccivic** [comment]
You want an entry in the changelog for a one character spelling mistake fix? Or do you just want me to tick the box above?

**Comment by Miffyli** [comment]
> You want an entry in the changelog for a one character spelling mistake fix? Or do you just want me to tick the box above?

An entry to changelog + updated contributors. A contribution is contribution, and all changes should be reflected in the changelog :)

**Comment by araffin** [comment]
Closing in favor of https://github.com/Stable-Baselines-Team/stable-baselines/pull/3 (will be merged soon)

**Pull request closed without merging**
