### PR TITLE
Fix - sample type inconsistency in (Multi)Categorical Probability Distribution

### PR DESCRIPTION
**Pull request by seheevic**
## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/hill-a/stable-baselines/blob/master/CONTRIBUTING.md) for new features and bug fixes)
closes https://github.com/hill-a/stable-baselines/issues/589

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/hill-a/stable-baselines/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the [changelog](https://github.com/hill-a/stable-baselines/blob/master/docs/misc/changelog.rst) accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [x] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [ ] I have ensured `pytest` and `pytype` both pass.

### CODE REVIEW

**Comment by Miffyli** [comment]
Thanks for the PR! However this could have been discussed further in the issue before opening a PR. Namely: I do not think the probability distributions should return `int32`s, as the default value for integers (in indexing/slicing) seems to be `long / int64` in TF/PyTorch. 

And more importantly, [Gym spaces](https://github.com/openai/gym/blob/master/gym/spaces/multi_discrete.py#L33) use `int64`. Rather than updating sampling to return `int32` I think they should return `int64` as previously but change the `sample_dtype`.

**Comment by seheevic** [comment]
@Miffyli 
As you said, I should have discussed more on the issue thread.
I just think that this is trivial bug because my modification is not by my own preference but from other code of this repository as you can see below:
- CategoricalProbabilityDistributionType already assumes sample type of tf.int32
https://github.com/hill-a/stable-baselines/blob/b461adb4d1abade945ba74e406817035cc683049/stable_baselines/common/distributions.py#L157-L181

- MultiCategoricalProbabilityDistributionType already assumes sample type of tf.int32
https://github.com/hill-a/stable-baselines/blob/b461adb4d1abade945ba74e406817035cc683049/stable_baselines/common/distributions.py#L184-L214

- MultiCategoricalProbabilityDistribution already returns sample of tf.int32
https://github.com/hill-a/stable-baselines/blob/b461adb4d1abade945ba74e406817035cc683049/stable_baselines/common/distributions.py#L355-L356
https://github.com/hill-a/stable-baselines/blob/b461adb4d1abade945ba74e406817035cc683049/stable_baselines/common/distributions.py#L367-L368

Practically, I think it would be better to use tf.int32, but if other libraries are going to int64, then some parameter could help me (who stick to int32 for service issue).
Anyway sorry about this hurry PR.

**Comment by Miffyli** [comment]
I would switch to using `int64` around the code for the consistency with Gym and the libraries (have to double check this is the case, though. I recall integers are `int64` by default in TF/PyTorch, but I am not 100% sure).

@araffin 

Any comments on this? Something I am missing?

**Comment by araffin** [comment]
>Something I am missing?

I don't think so, or at least, I'm not aware. Yes, I'm for the consistency ;)

**Comment by seheevic** [comment]
Ok, I got it.
Then may I close this PR?

**Comment by araffin** [comment]
>Then may I close this PR?

Well, you can do the changes on that PR, no need to close it.

**Comment by seheevic** [comment]
@Miffyli
Ok, now tf.int32 becomes tf.int64.

**Pull request merged**
