### PR TITLE
Fixed parameter order for compute_reward

### LINKED ISSUE #728: [Bug] Signature of GoalEnv.compute_reward  not matched in HER replay-buffer code
the openai-gym signature of GoalEnv.compute_reward(self, achieved_goal, desired_goal, info) is not matched correctly in her/replay_buffer.py line 176
```python
reward = self.env.compute_reward(goal, next_obs_dict['achieved_goal'], None)
```
this is a minor issue and has no effect in the combination with standard environments. but can lead to errors when the reward is not symmetric regarding desired_goal and achieved_goal.

Regards
Johannes

### PR DESCRIPTION
**Pull request by johannes-dornheim**
the openai-gym signature compute_reward(self, achieved_goal, desired_goal, info) was not matched, which leads to errors when the reward is not symmetric regarding desired_goal and achieved_goal.

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/hill-a/stable-baselines/blob/master/CONTRIBUTING.md) for new features and bug fixes)

closes #728 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/hill-a/stable-baselines/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the [changelog](https://github.com/hill-a/stable-baselines/blob/master/docs/misc/changelog.rst) accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [ ] I have ensured `pytest` and `pytype` both pass (by running  `make pytest` and `make type`).

### CODE REVIEW

**Comment by johannes-dornheim** [comment]
the openai-gym signature compute_reward(self, achieved_goal, desired_goal, info) was not matched, which leads to errors when the reward is not symmetric regarding desired_goal and achieved_goal.

**Comment by araffin** [comment]
Hello,
Thanks for the PR, but please actually check the boxes if you did what is written...

**Comment by johannes-dornheim** [comment]
Hi,

Sry that I forgot to create the according issue earlier. Now ive done so.

**Comment by araffin** [comment]
LGTM, if you read the contribution guide, then you know what is missing for it to be merged...

**Pull request merged**
