### PR TITLE
test python 2.7 compatibility

### PR DESCRIPTION
**Pull request by ClementRolinat**
make stable-baselines compatible with python 2.7.
only test_atari are failing because of a csv error in monitor.py.

### CODE REVIEW

**Comment by araffin** [comment]
Hello,

First, I recommend you reading `CONTRIBUTING.md`.

I'm not sure that python 2 compatibility is something we want. Although I understand that some systems (e.g. ROS) requires python 2, making the connection between SB and the application is bit tedious, my main concern is that python 2 will reach its end of life in 10 months (see [countdown](https://pythonclock.org/)).

**Comment by ClementRolinat** [comment]
Hello,

I will check contributing.md out, thanks.

I plan to use this library with ros, that is why I started this work. I think other people of the ros community may be interested by a 2.7 compatibility.

**Comment by HareshMiriyala** [comment]
This will be a useful feature. I'm currently working with the gazebo-gym environments and they dont support python3 yet because ros doesn't. :(

**Comment by araffin** [comment]
@ClementRolinat @HareshMiriyala For working with ROS + stable-baselines, I recommend you looking at the [S-RL Toolbox](https://github.com/araffin/robotics-rl-srl), especially [working with real robot](https://s-rl-toolbox.readthedocs.io/en/latest/guide/real_robots.html). We have created different script for interfacing with ROS/gazebo.

The simplest solution is to communicate with python 2 using a zmq sockets.

**Comment by HareshMiriyala** [comment]
@araffin  thanks ! btw, i found gym-gazebo does support python3

**Comment by araffin** [comment]
Closing this PR because python 2 won't be maintain anymore. But this will still appear in the repo so people can take a look at if they really need to use python 2 ;)

**Pull request closed without merging**
