### PR TITLE
Fix CloudpickleWrapper load-save asymmetry

### LINKED ISSUE #937: Asymmetric CloudPickleWrapper.__setstate__
Set state uses `pickle.loads`, but getstate uses `cloudpickle.dumps`. Fixed by #935.

This led to some pickle protocol errors when I was multiprocessing jobs via Ray, although I don't know why VecEnvs were being pickled at all in that case.

### PR DESCRIPTION
**Pull request by shwang**
## Description

CloudpickleWrapper loads using `pickle.loads`, and saves using `cloudpickle.dumps`. Using this codepath would lead to protocol error before this commit, since `pickle.loads` can't read `cloudpickle.dumps`.

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/hill-a/stable-baselines/blob/master/CONTRIBUTING.md) for new features and bug fixes)

Resolves #937.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/hill-a/stable-baselines/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the [changelog](https://github.com/hill-a/stable-baselines/blob/master/docs/misc/changelog.rst) accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [ ] I have ensured `pytest` and `pytype` both pass (by running  `make pytest` and `make type`).

### CODE REVIEW

**Comment by Miffyli** [comment]
Good catch! Please, fill in the points in PR template and this is good to go :)

**Comment by shwang** [comment]
This change seems small enough that it might not actually require tests (also I'm not even sure how I ran into the pickling protocol error in the first place, aside from the fact that I was using Ray and I upgraded my packages recently (are VecEnvs even supposed to be pickled when a lot of envs aren't actually picklable in the first place?)).

I'm down to figure out a test if the maintainers insist on this before merging though.

**Comment by araffin** [comment]
@shwang this issue may be present in SB3 too... would you mind doing the same PR? (should be fairly quick)

**Comment by shwang** [comment]
Yes, I can do that

**Pull request merged**
