### PR TITLE
Update ppo2 documentation

### PR DESCRIPTION
**Pull request by kvenkman**
## Description

Minor fix in the documentation
## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/hill-a/stable-baselines/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Documentation (update in the documentation)

## Checklist:

- [X] I've read the [CONTRIBUTION](https://github.com/hill-a/stable-baselines/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the [changelog](https://github.com/hill-a/stable-baselines/blob/master/docs/misc/changelog.rst) accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [X] I have updated the documentation accordingly.
- [ ] I have ensured `pytest` and `pytype` both pass (by running  `make pytest` and `make type`).

### CODE REVIEW

**Comment by Miffyli** [comment]
Good catch. Remember to check the contribution guide, specifically the parts about updating changelog with contributor's names :).

Looks like the docs could use bit better grammar-check than just individual words, as done previously.

**Comment by kvenkman** [comment]
Oh right. I'll change that and create a separate pull request. 

Should I just go ahead and do a grammar check on the docs, or is there an open issue regarding this?

**Comment by araffin** [comment]
You can push new commit in this PR, you don't have to create a new one ;)

**Comment by kvenkman** [comment]
Right, I'll do that. Thanks for stepping me through the process! :)

**Comment by araffin** [comment]
>Should I just go ahead and do a grammar check on the docs, or is there an open issue regarding this?

yes, please do, you don't have to open an issue for documentation fix ;)

**Comment by araffin** [comment]
>Should I just go ahead and do a grammar check on the docs, or is there an open issue regarding this?

Any news regarding that point?

**Comment by kvenkman** [comment]
Not yet. I'll commit my changes in the next day or so.

**Comment by araffin** [comment]
I will merge this one once travis finishes. Please do another PR for the grammar check.

**Pull request merged**
