### PR TITLE
Fix one typo. "Stabe" -> "Stable"

### PR DESCRIPTION
**Pull request by ColinLeongUDRI**
## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/hill-a/stable-baselines/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/hill-a/stable-baselines/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the [changelog](https://github.com/hill-a/stable-baselines/blob/master/docs/misc/changelog.rst) accordingly (**required**).
- [x] My change requires a change to the documentation.
~~- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).~~ (N/A)
- [x] I have updated the documentation accordingly.
~~- [ ] I have ensured `pytest` and `pytype` both pass (by running  `make pytest` and `make type`).~~ (not required)

### CODE REVIEW

**Comment by Miffyli** [comment]
Thanks for the PR! Please fulfil the steps in the PR template, namely updating changelog and contributors list.

**Comment by ColinLeongUDRI** [comment]
> 
> 
> Thanks for the PR! Please fulfil the steps in the PR template, namely updating changelog and contributors list.

I updated the changelog.rst linked in the checklist above, but cannot seem to find the contributors list. I looked through the docs folder and searched the repo, but cannot seem to find it. Where would that be? 

Also I don't have the capability to run `make pytest` and `make type`, I'm afraid.

**Comment by Miffyli** [comment]
> Where would that be?

It is at the very end of the `changelog.rst` file.

> Also I don't have the capability to run make pytest and make type, I'm afraid.

Those are not necessary for this update :)

**Comment by ColinLeongUDRI** [comment]
Name added! I think that's everything.

**Comment by ColinLeongUDRI** [comment]
...and thank you for your patient explanations.

**Comment by Miffyli** [comment]
@araffin 

Weird test error out of nowhere: https://travis-ci.com/github/hill-a/stable-baselines/jobs/356568081

**Comment by araffin** [comment]
> @araffin
> 
> Weird test error out of nowhere: https://travis-ci.com/github/hill-a/stable-baselines/jobs/356568081

just bad luck... I restarted the job, should pass now.

**Pull request merged**
