### PR TITLE
Make MPI install optional

### LINKED ISSUE #430: [feature request] Import MPI only when needed
**Describe the bug**
Only four (DDPG, GAIL, TRPO and PPO1) of the twelve algorithms implemented in Stable Baselines use MPI. However, importing `stable_baselines` -- even if you do not use any of the algorithms -- indirectly executes `from mpi4py import MPI`.

This has a number of issues:
  - `mpi4py` has a binary dependency on OpenMPI, which often needs to be installed especially.
  - In some installations of OpenMPI, any code that uses MPI must be executed under `mpirun`, even if you only use a single process.
  - OpenMPI is unreliable, and interacts particularly poorly with multi-threading (e.g. TensorFlow) and multi-processing (e.g. `SubprocVecEnv`).

**Code example**
I've run into many issues with OpenMPI over time. Never tracked down the root cause satisfactorily. As a recent example, https://github.com/HumanCompatibleAI/imitation/blob/master/src/imitation/scripts/train.py deadlocked inside OpenMPI on Ubuntu 18.04 with OpenMPI 2. It worked fine on a recent Mac OS X install. Previously I've also had issues with OpenMPI 4, and found OpenMPI 3 seems to be the most reliable version.

@shwang @qxcv may have more details on this failure mode.

**Suggested Resolution**
The two main options I see are:
  - Change `stable_baselines/__init__.py` to not automatically import all the algorithms. This seems the cleanest, but would introduce a breaking API change: users would need to do e.g. `from stable_baselines.ppo1 import PPO1` rather than `from stable_baselines import PPO1`. It would speed up importing `stable_baselines` though, which right now takes a while.
  - Change all files that use MPI to import it lazily. This should be fairly easily: most the time it's only used in one function in each file. It would make things a bit more fragile: if `mpi4py` wasn't installed, you would only get an error when you actually run the algorithm.

I'm happy to open a PR on this if there's agreement on if/how to resolve this.

### PR DESCRIPTION
**Pull request by shwang**
closes #430

### CODE REVIEW

**Comment by araffin** [comment]
Hello,
Thanks for the PR. The failure on Travis seems to come from the recent update of the docker images... (Cf #428)
If the issue is not identified, i will rollback to the previous docker image.

**Comment by AdamGleave** [comment]
`docs/misc/changelog.rst` should be updated to mention this.

It'd be nice to test things work as expected with or without `mpi4py` installed. Ideal would be to run Travis in two environments, but that'd be quite expensive, and we'd need to go through and disable the relevant tests. 

Just checking you can import `stable_baselines` without import errors if `mpi4py` is not installed would catch a lot of potential issues. I think something like this should work:
```
import sys

def test_no_mpi():
  mpi = sys.modules['mpi4py']
  sys.modules['mpi4py'] = None
  import stable_baselines
  # ... maybe do some simple smoke test in something in stable_baselines
  sys.modules['mpi4py'] = mpi  # only need to do this if process reused
```

**Comment by araffin** [comment]
@AdamGleave @shwang to test travis for now, you can use the v2.6.0 docker images (see https://github.com/hill-a/stable-baselines/pull/428/commits/d7e95915f7a77f7f0ad357009d1c71a4d63f1cc3), I'm trying to find out what dependency makes it fail (it looks like it is pytest fault).

**Comment by araffin** [comment]
I rolled back the docker images for now, travis should be working again

**Comment by AdamGleave** [comment]
@shwang is this ready for review?

**Comment by shwang** [comment]
Need to add a test, not yet.

Thanks for the rollback, @araffin

**Comment by AdamGleave** [comment]
> Need to add a test, not yet. Thanks for the rollback, @araffin
OK, ping me when you want me to take a look.

**Comment by shwang** [comment]
`del sys.modules["mpi4py"]` actually matters in the `test_logger` because `misc_util.mpi_rank_or_zero()` imports mpi4py inside the function definition.

I also considered adding a `disabled_mpi` parametrization to test_ppo2 but that doesn't seem to add anything substantive.

**Comment by shwang** [comment]
@AdamGleave ready for review

**Comment by araffin** [comment]
A bit late... I thought the README was also updated but this is not the case.
I also need to check colab notebook to ensure stable baselines with mpi is installed.

**Comment by AdamGleave** [comment]
Ah, sorry for not catching that README.md wasn't updated, I've opened a new PR.

**Pull request merged**
