### PR TITLE
PPO cpp project 

### LINKED ISSUE #513: [question] Exporting trained agent into c/c++ code
Is it possible to export a trained agent/model into a C/C++ code?

### PR DESCRIPTION
**Pull request by Antymon**
Adding personal project dependant on Stable Baselines to the docs ([link](https://github.com/Antymon/ppo_cpp)).

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/hill-a/stable-baselines/blob/master/CONTRIBUTING.md) for new features and bug fixes)

closes #513 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/hill-a/stable-baselines/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the [changelog](https://github.com/hill-a/stable-baselines/blob/master/docs/misc/changelog.rst) accordingly (**required**).
- [x] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [x] I have updated the documentation accordingly.
- [ ] I have ensured `pytest` and `pytype` both pass.

### CODE REVIEW

**Comment by araffin** [comment]
Hello,
Thanks for the PR, please don't forget the changelog.
Btw, it seems that this is related to #513 , so you can also update this [section](https://stable-baselines.readthedocs.io/en/master/guide/export.html) of the doc ;)

**Comment by Antymon** [comment]
Oh, I could expand that section on C++, but it would quickly boil down to saying it will require some work of you if you want to do it and pointing at my work as an example.

**Comment by araffin** [comment]
>Oh, I could expand that section on C++, but it would quickly boil down to saying it will require some work of you if you want to do it and pointing at my work as an example.

Sounds good, this is only meant to provide starter material (not complete tutorial) for someone who wants to export his model to C++.

**Comment by Antymon** [comment]
I resolved changelog conflicts. 
I understand that C++ portability suggestions are out of scope of this PR.

**Comment by araffin** [comment]
Please still put a link to your project in the export model section ;) (plus one or two sentences)

**Comment by Antymon** [comment]
Here you go.

**Comment by araffin** [comment]
I bypassed Codacy because no changes to the code were made.

**Pull request merged**
