### PR TITLE
Roboy project

### PR DESCRIPTION
**Pull request by ALPA-Industry-and-Technology**
Hello,

I added a few lines regarding our semester project about reinforcement learning by Roboy.
Roboy is a tendon-driven robot build by a student group of the TU Munich.

### CODE REVIEW

**Comment by araffin** [comment]
Hi Alex,

look good to me except that you should put it at the bottom of the page, not top ;)

**Comment by ALPA-Industry-and-Technology** [comment]
Thank you for looking over it!

I will fix it!

________________________________
Von: Antonin RAFFIN <notifications@github.com>
Gesendet: Mittwoch, 17. April 2019 13:55:05
An: hill-a/stable-baselines
Cc: Pakakis, Alexander; Author
Betreff: Re: [hill-a/stable-baselines] semester project by TU Munich (#280)


Hi Alex,

look good to me except that you should put it at the bottom of the page, not top ;)

**Comment by ALPA-Industry-and-Technology** [comment]
-> done!

**Comment by araffin** [comment]
oh, you did not see my edit because of emails...
so:
did you add the video? and it would be nice to write what was done rather than what you want to do ;)

**Comment by ALPA-Industry-and-Technology** [comment]
-> done

**Pull request merged**
