### PR TITLE
hotfix broken import stable_baselines

### PR DESCRIPTION
**Pull request by shwang**
The tests in `test_no_mpi.py` didn't actually check whether we can `import stable_baselines` with MPI uninstalled because `import stable_baselines` simply loads `stable_baselines` from the `sys.modules` cache.

This PR uses a recursive reload of stable_baselines to ensure that each auto-imported file in the `stable_baselines` module can be loaded without error.

### CODE REVIEW

**Comment by shwang** [comment]
Now we correctly get an ImportError:
```
ImportError while importing test module '/home/steven/stable-baselines/tests/test_no_mpi.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_no_mpi.py:5: in <module>
    import stable_baselines
stable_baselines/__init__.py:7: in <module>
    from stable_baselines.td3 import TD3
stable_baselines/td3/__init__.py:3: in <module>
    from stable_baselines.ddpg.noise import NormalActionNoise, OrnsteinUhlenbeckActionNoise
stable_baselines/ddpg/__init__.py:1: in <module>
    from stable_baselines.ddpg.ddpg import DDPG
stable_baselines/ddpg/ddpg.py:12: in <module>
    from mpi4py import MPI
E   ModuleNotFoundError: No module named 'mpi4py'
```

**Comment by shwang** [comment]
The source of the error is a ddpg import (mpi4py) in `stable_baselines/td3/__init__.py`.
```
from stable_baselines.ddpg.noise import NormalActionNoise, OrnsteinUhlenbeckActionNoise
```

I patched this here by moving `ddpg.noise` to `common.noise`. This decouples `*ActionNoise` from the TD3 dependency.

Other possible solutions:
  * Remove`ddpg.noise.*ActionNoise` imports from `td3/__init__.py`. (A quick `git grep ActionNoise` didn't show anything in the codebase accessing `*ActionNoise` via `stable_baselines.td3.*ActionNoise`.)
  * Only import `*ActionNoise` in `td3` if `mpi4py` is installed.

**Comment by araffin** [comment]
Hello,
In fact, we had that discussion with @hill-a with the td3 pr. Moving to common is the best option i think.
For completely not breaking the api, you should keep the noise file in ddpg but import the noises from common in that file too.

**Comment by AdamGleave** [comment]
Thanks for catching this mistake. The recursive reload seems quite complex. Ideally we'd just run that test in a fresh Python interpreter, but seems hard to do with `pytest. I think a simpler solution is to delete `stable_baselines` and all submodules from `sys.modules` as in https://stackoverflow.com/questions/45462374/mark-test-to-be-run-in-independent-process I've pushed a change that does this, but I may well have missed a subtlety, so feel free to revert if this is worse.

**Comment by shwang** [comment]
> Thanks for catching this mistake. The recursive reload seems quite complex. Ideally we'd just run that test in a fresh Python interpreter, but seems hard to do with `pytest. I think a simpler solution is to delete `stable_baselines`and all submodules from`sys.modules` as in https://stackoverflow.com/questions/45462374/mark-test-to-be-run-in-independent-process I've pushed a change that does this, but I may well have missed a subtlety, so feel free to revert if this is worse.

Nice this simpler solution is working well!

**Comment by AdamGleave** [comment]
It looks like there's a lot of breakage in seemingly unrelated tests from this. My guess is we somehow have different versions of imported `stable_baselines` floating around after this, which causes issues with uses of `isinstance` and `issubclass`.

Not sure how to fix this, unfortunately. Could try changing `test_no_mpi` to restore the original `sys.modules` at the end of the test.

**Comment by araffin** [comment]
I usually have that kind of error using jupyter notebook with autoreload when changing the modules that are imported into it. 
So, unfortunately, a quick fix is to put it at the end, I would be happy if you have a better solution ;).

**Comment by AdamGleave** [comment]
> I usually have that kind of error using jupyter notebook with autoreload when changing the modules that are imported into it.
> So, unfortunately, a quick fix is to put it at the end, I would be happy if you have a better solution ;).

Restoring sys.modules seeems to have fixed it

**Comment by AdamGleave** [comment]
@shwang do you want to update the docs? I think then we can merge.

**Comment by shwang** [comment]
@AdamGleave : Should be good now. Thanks for the reminder

**Pull request merged**
