### PR TITLE
PPO2: Fix nan episode reward and episode length

### LINKED ISSUE #24: Mean Episode Reward and Length showing NaN in PPO2 training.
Hello,

First of all I would like to thank you for this is incredibly polished package. Seeing good documentation just makes me feel happy.

While training PPO2 on Pong-ram-v0 (and several other envs) I realized that the episode reward doesn't print correctly to the console.  It is seen as follows:
screenshot from 2018-09-18 12-15-51

I tried looking into it but couldn't figure out why just yet. If you give me some pointers I would like to work on fixing it.

I am using python 3.6.5 on an Ubuntu 16.04.

### PR DESCRIPTION
**Pull request by shwang**
Example output:
```
----------------------------------------
| approxkl            | 0.0002786463   |
| clipfrac            | 0.0            |
| explained_variance  | 0.0322         |
| fps                 | 2494           |
| mean_episode_length | 111            |
| mean_episode_reward | 111            |
| nupdates            | 24             |
| policy_entropy      | 0.5853524      |
| policy_loss         | -0.00097488245 |
| serial_timesteps    | 3072           |
| time_elapsed        | 11             |
| total_timesteps     | 24576          |
| value_loss          | 73.03953       |
----------------------------------------
```

Closes #24.

### CODE REVIEW

**Comment by araffin** [comment]
Quick question: does it gives the true reward also when using vecnormalize?

**Comment by sirspinach** [comment]
No, doesn't look like it. Here's a screencap for the same environment (CartPole):

image

**Comment by araffin** [comment]
Ok, so in that case i would not delete the reward that comes from the monitor, having the true reward is quite important for monitoring. @hill-a what do you think of that?
Another solution would be to create a monitor warpper automatically but i don t really like that option.

**Comment by araffin** [comment]
Hello,

as this PR did change for quite a long time and now no NaN are displayed if there is no Monitor wrapper, I will close it for now.

**Pull request closed without merging**
