### PR TITLE
Update custom env doc to match gym API

### LINKED ISSUE #596: Small error in custom environment documentation
Your custom gym environment documentation doesn't quite agree with open ai's:

[Yours](https://stable-baselines.readthedocs.io/en/master/guide/custom_env.html) has closing the render be an argument to render: 

`def render(self, mode='human', close=False):`

[Theirs](https://github.com/openai/gym/blob/master/docs/creating-environments.md) (which you link to as well) has close be it's own method, and that form is reflected in other libraries as well.

I'll submit a PR for this provided I'm not somehow crazy and you tell me where the documentation is.

### PR DESCRIPTION
**Pull request by justinkterry**
Description
Motivation and Context
Closes #596
Types of changes

- [ ]  Bug fix (non-breaking change which fixes an issue)
- [ ]  New feature (non-breaking change which adds functionality)
- [ ]  Breaking change (fix or feature that would cause existing functionality to change)
- [x]  Documentation (update in the documentation)

Checklist:

- [x]  I've read the CONTRIBUTION guide (required)
- [x]  I have updated the changelog accordingly (required).
- [ ]  My change requires a change to the documentation.
- [ ]  I have updated the tests accordingly (required for a bug fix or a new feature).
- [x]  I have updated the documentation accordingly.
- [x]  I have ensured pytest and pytype both pass.

### CODE REVIEW

**Comment by araffin** [comment]
Thanks for the PR but please fill the PR template

**Comment by justinkterry** [comment]
Done in edit

**Comment by justinkterry** [comment]
Do you need anything else from me to merge this?

**Comment by araffin** [comment]
I give you a hint: there are required fields in the PR template ;) (that's also why we ask contributors to fill it)

**Comment by justinkterry** [comment]
Done, sorry.

**Pull request merged**
