### PR TITLE
Add stable-baselines-tf2 to project list page.

### LINKED ISSUE #984: I added TF2.x support for stable-baselines
This is not really an issue but I'd like to let you know that I created a repo for supporting stable-baselines in TF2.x with minimum amount of changes: https://github.com/sophiagu/stable-baselines-tf2
I've tested that repo both on a local machine and in a third party environment.

Hope this will be of help to other people who are using TF2 and Stable Baselines!

### PR DESCRIPTION
**Pull request by sophiagu**
## Description

closes #984 

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/hill-a/stable-baselines/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/hill-a/stable-baselines/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the [changelog](https://github.com/hill-a/stable-baselines/blob/master/docs/misc/changelog.rst) accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [ ] I have ensured `pytest` and `pytype` both pass (by running  `make pytest` and `make type`).

### CODE REVIEW

**Comment by Miffyli** [comment]
Please fill in the checklist (e.g. update changelog and include username).

**Comment by sophiagu** [comment]
The latest release date in changelog is 2020-08-05. Should I add changes under this release date or add a new release date?

**Comment by Miffyli** [comment]
@araffin Could you answer the above?

**Comment by sophiagu** [comment]
This is a unit test failure which seems to be irrelevant to my changes: https://travis-ci.com/github/hill-a/stable-baselines/jobs/377081203

**Comment by araffin** [comment]
>The latest release date in changelog is 2020-08-05. Should I add changes under this release date or create a new release date?

I added a new section for it ;)

**Comment by sophiagu** [comment]
pending review?

**Comment by Miffyli** [comment]
Could you add your alias to the changelog as instructed in the contributor's guide. After that this seems ready for merging :)

**Comment by sophiagu** [comment]
Thx!!

**Review by Miffyli — APPROVED** [review]

**Pull request merged**
