### PR TITLE
Corrected divide by zero in DQN's epsilon anneal

### PR DESCRIPTION
**Pull request by Solliet**
Introduced a new variable in DQNs constructor to dictate how long exploration steps will be annealed for. 

## Description
The variable in DQN's constructor has default value None and is used when creating a linear schedule in `DQN.learn`. If the value is None, then the LinearSchedule is backwards compatible and uses the `total_timesteps` variable that is provided in `dqn.learn`. If the value is something else that value is used instead.

## Motivation and Context
- [x] I have raised an issue to propose this change ([required](https://github.com/hill-a/stable-baselines/blob/master/CONTRIBUTING.md) for new features and bug fixes)
Solves #756.

This solves two issues. First, the divide by zero mentioned in #756.

Second, it solves the case where we interleave a few training steps with other code and want to continue annealing exploration: 

Without the change:

```python
agent.learn(1000)
# other stuff

# exploration is always equal to `exploration_final_eps`
# because we we have already done 1000 steps
agent.learn(1000)
```

In the above scenario, the exploration rate will anneal from initial value to final value over 1000 steps. On the second call, the exploration rate will be equal to `exploration_final_eps` because:

```python
update_eps = self.exploration.value(self.num_timesteps)
```
Thus exploration annealing halts.

With the change:

```python

agent = DQN(..., exploration_annealing_steps = 2000) 
agent.learn(1000)
# other stuff
agent.learn(1000) # epsilon annealing continues
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/hill-a/stable-baselines/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the [changelog](https://github.com/hill-a/stable-baselines/blob/master/docs/misc/changelog.rst) accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [ ] I have ensured `pytest` and `pytype` both pass (by running  `make pytest` and `make type`).

### CODE REVIEW

**Comment by Miffyli** [comment]
I will continue the discussion of #756 here. 

While this fixes the issue raised here, it becomes rather confusing having the parameters in two places. Preferably, all exploration parameters should be provided in the `learn` call, but in that case they can not be saved along the model. This would be a rather large change to paradigm of how agents work, again.

@araffin Comments on this?

**Comment by Solliet** [comment]
I am not sure how this is a breaking change.

**Comment by Solliet** [comment]
Because this is a minor change, it's easy to move the parameter to `.learn` if that's better. As @Miffyli mentioed in #756, some type of assertion or sanity check would be quite useful here but I am unsure as to what's the best way to introduce that.

**Comment by araffin** [comment]
Closing this PR according to discussion in #756 . (that's also why I prefer to discuss first and open the PR afterward, when we reach an agreement on how to solve the issue)

**Pull request closed without merging**
