### PR TITLE
Copy version.txt to docker container

### PR DESCRIPTION
**Pull request by anj1**
This PR fixes https://github.com/hill-a/stable-baselines/issues/1066

### CODE REVIEW

**Comment by araffin** [comment]
Hello,
thanks for the PR, please don't forget to fill the PR template completely next time ;)

**Review by araffin — APPROVED** [review]
LGTM =)

**Comment by anj1** [comment]
Ok will do

**Comment by araffin** [comment]
We are having some trouble with travis-ci (which no longer supports open source projects :cry: )
@hill-a could deactivate temporary travis-ci check so I can merge that one?

I will see how to switch to github actions in another PR probably.

**Comment by araffin** [comment]
Merged in https://github.com/Stable-Baselines-Team/stable-baselines/pull/2

**Pull request closed without merging**
