### PR TITLE
Fixed CustomPolicy documentation so it will run.

### PR DESCRIPTION
**Pull request by Bleyddyn**
I'm not sure this is the best way to fix this, but it now runs, as is, in a Google Colab notebook.

### CODE REVIEW

**Comment by araffin** [comment]
Hello,
Thanks for your PR, yes custom policy example needs to be updated.
I would rather use `make_atari_env`(instead of `wrap_deepmind`) as in the [examples](https://stable-baselines.readthedocs.io/en/master/guide/examples.html#id1).
and you should use `self.processed_obs` (as [here][https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/policies.py#L401)) otherwise, no normalization is applied on images.

**Comment by Bleyddyn** [comment]
@araffin I did try using self.processed_obs but got an error that it didn't exist (see below). I'll try make_atari_env again, but I think I was getting errors with that too.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-d75439d68d9d> in <module>()
     47 env = DummyVecEnv([lambda: env])
     48 
---> 49 model = A2C(CustomPolicy, env, verbose=1)
     50 # Train the agent
     51 model.learn(total_timesteps=100000)

/usr/local/lib/python3.6/dist-packages/stable_baselines/a2c/a2c.py in __init__(self, policy, env, gamma, n_steps, vf_coef, ent_coef, max_grad_norm, learning_rate, alpha, epsilon, lr_schedule, verbose, tensorboard_log, _init_setup_model)
     79         # if we are loading, it is possible the environment is not known, however the obs and action space are known
     80         if _init_setup_model:
---> 81             self.setup_model()
     82 
     83     def setup_model(self):

/usr/local/lib/python3.6/dist-packages/stable_baselines/a2c/a2c.py in setup_model(self)
    100 
    101                 step_model = self.policy(self.sess, self.observation_space, self.action_space, self.n_envs, 1,
--> 102                                          n_batch_step, reuse=False)
    103 
    104                 with tf.variable_scope("train_model", reuse=True,

<ipython-input-7-d75439d68d9d> in __init__(self, sess, ob_space, ac_space, n_env, n_steps, n_batch, reuse, **kwargs)
     12             activ = tf.nn.relu
     13 
---> 14             extracted_features = nature_cnn(self.processed_obs, **kwargs)
     15             extracted_features = tf.layers.flatten(extracted_features)
     16 

AttributeError: 'CustomPolicy' object has no attribute 'processed_obs'

**Comment by Bleyddyn** [comment]
Ok. The current version is now running in Google Colab.

**Comment by araffin** [comment]
I think i know where your problem comes from, your are not using the current master version that will be released soon, to allow installation via pip (the documentation corresponds to that version).
Anyway, there was a typo (self.self.... instead of self.processed_obs) so i would still appreciate a PR that fixes that.

Please open an issue first next time ;)
(A contribution guide (see current PRs) will be merged with master soon )

**Comment by araffin** [comment]
I've updated the example in #160 and added your name to the contributors list ;)
Therefore, closing this PR. Your problem with `self.processed_obs` can be solved in two ways:
- install stable-baselines from source
- wait a bit for the 2.4.0 release (this week normally)

**Pull request closed without merging**
