### PR TITLE
Fix re-training with different number of environments

### LINKED ISSUE #1132: Fix for PPO2 When loading a model and then training with vectorized environment with a different vector length
**Describe the bug**
Lets say you train PPO2 with a vectorized environment of length 2, then you save and load the model and train with a vectorized environment of size 1. A crash occurs.

**Code example**

```python

    env = make_vec_env('CartPole-v1',n_envs=2)
    model = PPO2('MlpPolicy', env, n_steps = 10, nminibatches=1)
    
    model.learn(total_timesteps = 100)
    model.save("ppo2_cartpole")
    
    del model
    
    model = PPO2.load("ppo2_cartpole")
    test_env = DummyVecEnv([lambda: gym.make('CartPole-v1')])
    
    model.set_env(test_env)
    model.learn(total_timesteps = 100)

```
**Error**
```bash
slices = (arr[mbinds] for arr in (obs, returns, masks, actions, values, neglogpacs))
E   IndexError: index 13 is out of bounds for axis 0 with size 10

stable_baselines/ppo2/ppo2.py:362: IndexError


```

**System Info**
*development build from source(this error should be easy to reproduce with any build)*
*python3.7*

**Additional context**
I have prepped a pull request with the patch and corresponding test. The test will fail when the patch is not applied. It may come down to opinion whether this is an error or not, but I think it is, since n_batch depends on n_envs and there does not seems to be a mechanism for updating n_batch outside of initialization. I am interested to hear the thoughts of the maintainers on this proposed patch.

### PR DESCRIPTION
**Pull request by balisujohn**
A patch fixing the ability of a loaded PPO2 model to further train on a vectorized environment of a different length than the one it was initially trained on. 

## Description

A test was added to test_ppo2.py which tests the ability of a loaded PPO2 model to train on a vectorized environment of a different length than the one it was initially trained on. 
set_env was overridden in ppo2.py to explicitly update n_batch to equal n_envs * n_steps as well as calling the set_env function of the super class.

## Motivation and Context
Prior to this patch, the code in the issue in the linked pull request will fail, the patch aims to fix that. 
closes #1132 
- [x] I have raised an issue to propose this change ([required](https://github.com/hill-a/stable-baselines/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/hill-a/stable-baselines/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the [changelog](https://github.com/hill-a/stable-baselines/blob/master/docs/misc/changelog.rst) accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [x] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [ ] I have ensured `pytest` and `pytype` both pass (by running  `make pytest` and `make type`).

### CODE REVIEW

**Comment by balisujohn** [comment]
Also possibly worth noting, I tried to reproduce this error with stablebaselines3 since development is more active there and it seems like stablebaselines3 can handle at least a simple version of this situation without crashing.

`
#derived from https://github.com/DLR-RM/stable-baselines3


import gym

from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.env_util import make_vec_env


env = make_vec_env("CartPole-v1", n_envs=4)


model = PPO("MlpPolicy", env,verbose=1, n_steps = 10)
model.learn(total_timesteps=10000)


model.save("test_model")
del model


env =make_vec_env("CartPole-v1", n_envs=1)


model=PPO.load("test_model", env)

model.learn(total_timesteps = 10000)`


(ran without error)

**Comment by Miffyli** [comment]
Sorry for the delay! Indeed SB3 is more refined in this regard.

Seems like this issue could happen with other algos so they should be fixed as well (e.g. A2C).

@araffin thoughts on merging this? Seems like an appropriate maintenance mode fix.

**Comment by araffin** [comment]
>Sorry for the delay! Indeed SB3 is more refined in this regard.

yes, SB3 is the recommend solution.

>Seems like this issue could happen with other algos so they should be fixed as well (e.g. A2C).

yes, probably the case for all A2C-like algorithms (A2C, ACER, ACKTR and maybe TRPO).

It seems we also need to fix type annotation (the new version of pytype does not like when things are not properly marked as optional).

>@araffin thoughts on merging this? Seems like an appropriate maintenance mode fix.

I would be happy to merge it after the pytype issues are fixed (you can keep this PR to fix them).

Regarding the test, please use `tmp_path` pytest argument (automatic temp folder) rather than saving/loading in the same folder (I know that some tests do not use it, but should be the case in SB3 tests).

**Review by araffin — APPROVED** [review]
LGTM, thanks =)

**Pull request merged**
