### PR TITLE
Fixed eval/return and eval/Q bug

### LINKED ISSUE #225: ddpg learn eval/return and eval/Q should be mean?
In stable-baselines/ddpg/ddpg.py line 916 and 918 should the eval/return and eval/Q be np.mean to make scalar?
`# Evaluation statistics.`
`if self.eval_env is not None:`
`                        combined_stats['eval/return'] = eval_episode_rewards`
`                        combined_stats['eval/return_history'] = np.mean(eval_episode_rewards_history)`
`                        combined_stats['eval/Q'] = eval_qs`
`                        combined_stats['eval/episodes'] = len(eval_episode_rewards)`

### PR DESCRIPTION
**Pull request by keshaviyengar**
- Fix for bug issue [#225](https://github.com/hill-a/stable-baselines/issues/225)
- Ran tests with `./run_tests.sh`, all passed

Closes #225

### CODE REVIEW

**Comment by araffin** [comment]
Hello,
thanks for your PR.

Please add an entry to the changelog + add your name at the bottom (cf what @AdamGleave did [here](https://github.com/hill-a/stable-baselines/pull/207/files#diff-ef2e097f276c4d90973dbe2e8025caa7))
I would also add a test (to ensure that it works) to prevent from regression.

**Comment by araffin** [comment]
LGTM, only integration test missing.

**Comment by keshaviyengar** [comment]
Anything missing from this pull request?

**Comment by araffin** [comment]
>Anything missing from this pull request?

Yes, as written above, an "integration test [is] missing". I meant that you should add a test that will fail in the current master version and pass with your fix, this would avoid future regression.

**Comment by araffin** [comment]
@keshaviyengar I've written and pushed the test to your branch, will merge after the CI pass ;)

**Comment by keshaviyengar** [comment]
Ah sorry it took me awhile, I'll be quicker about it next time. Thanks @araffin

**Pull request merged**
